pipeline {
    agent any

    environment {
        AWS_REGION = "ap-south-1"
        IMAGE_NAME = "springboot-demo"
        IMAGE_TAG = "${BUILD_NUMBER}"
        ECR_REGISTRY = "452829727099.dkr.ecr.ap-south-1.amazonaws.com"
        ECR_REPO = "${ECR_REGISTRY}/${IMAGE_NAME}"
    }

    tools {
        maven 'Maven_3.8.5'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/rajatphoneix/argocd_cicd.git'
            }
        }

        stage('Test') {
            steps {
                dir('springboot-app') {
                    sh 'mvn test'
                }
            }
        }

         stage('Build') {
            steps {
                dir('springboot-app') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Docker Build & Push') {
            steps {
                dir('springboot-app') {
                    withAWS(credentials: 'aws-default', region: "${env.AWS_REGION}") {
                        sh """
                            aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}
                            docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
                            docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${ECR_REPO}:${IMAGE_TAG}
                            docker push ${ECR_REPO}:${IMAGE_TAG}
                        """
                    }
                }
            }
        }

      stage('Update YAML + Git Push') {
          steps {
              withCredentials([usernamePassword(credentialsId: 'github-push-creds', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PASS')]) {
                  sh '''
                      sed -i "s|^\\([[:space:]]*image:\\).*|\\1 '$ECR_REPO:$IMAGE_TAG'|" deployment/base/deployment.yaml

                      git config user.email "rajatphoneix@gmail.com"
                      git config user.name "rajatphoneix"
                      git remote set-url origin https://${GIT_USER}:${GIT_PASS}@github.com/rajatphoneix/argocd_cicd.git

                      git add deployment/base/deployment.yaml
                      git commit -m "Auto update: $IMAGE_TAG" || echo "No changes to commit"
                      git push origin main
                  '''
              }
          }
      }
    }
}
